music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
    # /music/ homepage
    url(r'^$', views.index, name='index'),

    #/login_user
    url(r'^login_user/$', views.login_user, name='login_user'),

    #/music/register
    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    #/music/logout
    url(r'^logout_user/$', views.logout_user, name='logout_user'),

    # /music/album_id
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name="detail"),

    #/music/album/add/
    url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),

    #/music/album/2/
    url(r'^album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name="album-update"),

    #/music/album/2/delete
     url(r'^album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name="album-delete"),

    #/music/song/add/
    url(r'^(?P<album_id>[0-9]+)/create_song/$', views.create_song, name='create_song'),

    #/music/song/2/
    url(r'^song/(?P<pk>[0-9]+)/$', views.SongUpdate.as_view(), name="song-update"),

    #/music/song/2/delete
     url(r'^(?P<album_id>[0-9]+)/delete_song/(?P<song_id>[0-9]+)/$', views.delete_song, name='delete_song'),

    #/music/images/
     url(r'^images/$', views.images, name='images'),

    #/music/album/add/
    url(r'images/add/$', views.ImagesCreate.as_view(), name='images-add'),

    #/music/song/2/
    url(r'^images/(?P<pk>[0-9]+)/$', views.ImagesUpdate.as_view(), name="images-update"),

    #/music/song/2/delete
     url(r'^images/(?P<pk>[0-9]+)/delete/$', views.ImagesDelete.as_view(), name="delete_images"),

     #/music/images/
     url(r'^videos/$', views.videos, name='videos'),

    #/music/album/add/
    url(r'videos/add/$', views.VideosCreate.as_view(), name='videos-add'),

    #/music/song/2/
    url(r'^videos/(?P<pk>[0-9]+)/$', views.VideosUpdate.as_view(), name="videos-update"),

    #/music/song/2/delete
     url(r'^videos/(?P<pk>[0-9]+)/delete/$', views.VideosDelete.as_view(), name="delete_videos"),

]

vivamedia/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField(blank=True)

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk':self.pk})

    def __str__(self):
        return self.album_title + ' - ' + self.artist

class Song(models.Model):
    album  = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    song_file = models.FileField()


    def __str__(self):
        return self.song_title

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk':self.album_id})

class Image(models.Model):
    image_title = models.CharField(max_length=250)
    image_file = models.FileField()

    def __str__(self):
        return self.image_title

    def get_absolute_url(self):
        return reverse('music:images')

class Video(models.Model):
    video_title = models.CharField(max_length=250)
    video_file = models.FileField()

    def __str__(self):
        return self.video_title

    def get_absolute_url(self):
        return reverse('music:videos')

music/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Album, Song

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)


    class Meta:
        model = User
        fields = ['username', 'email', 'password']

class SongForm(forms.ModelForm):

    class Meta:
        model = Song
        fields = ['song_title', 'song_file']

music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from .models import Album, Song, Image, Video
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View
from .forms import UserForm, SongForm
from django.http import HttpResponse
import os
from django.shortcuts import render, get_object_or_404
from django.db.models import Q


def index(request):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:
        albums = Album.objects.all()
        image = Image.objects.all()
        video = Video.objects.all()
        query = request.GET.get("q")
        if query:
            albums = albums.filter(
                Q(album_title__icontains=query) |
                Q(artist__icontains=query)
            ).distinct()

            image = image.filter(
                Q(image_title__icontains=query)
            ).distinct()

            video = video.filter(
                Q(video_title__icontains=query)
            ).distinct()

            return render(request, 'music/search.html', {
                'albums': albums,
                'image': image,
                'video': video,
            })
        else:
            return render(request, 'music/index.html', {'albums': albums})

class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'


class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre']

class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')

def create_song(request, album_id):
    form = SongForm(request.POST or None, request.FILES or None)
    album = get_object_or_404(Album, pk=album_id)
    if form.is_valid():
        albums_songs = album.song_set.all()
        song = form.save(commit=False)
        song.album = album
        song.save()
        return render(request, 'music/detail.html', {'album': album})
    context = {
        'album': album,
        'form': form,
    }
    return render(request, 'music/create_song.html', context)

class SongUpdate(UpdateView):
    model = Song
    fields = ['song_title', 'song_file']

def delete_song(request, album_id, song_id):
    album = get_object_or_404(Album, pk=album_id)
    song = Song.objects.get(pk=song_id)
    song.delete()
    return render(request, 'music/detail.html', {'album': album})


class UserFormView(View):
    form_class = UserForm
    template_name = 'music/registration_form.html'

    #display blank from
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    #process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)

            # cleaned (normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            # returns User objects if credentials are correct
            user = authenticate(username=username, password=password)

            if user is not None:

                if user.is_active:
                    login(request, user)
                    return redirect('music:index')
        return render(request, self.template_name, {'form': form})


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                albums = Album.objects.all()
                return render(request, 'music/index.html', {'albums': albums})
            else:
                return render(request, 'music/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'music/login.html', {'error_message': 'Invalid login'})
    return render(request, 'music/login.html')


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'music/login.html', context)


def images(request):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:
        image = Image.objects.all()

        return render(request, 'music/images.html', {
            'image': image,
            })


class ImagesCreate(CreateView):
    model = Image
    fields = ['image_title', 'image_file']

class ImagesUpdate(UpdateView):
    model = Image
    fields = ['image_title', 'image_file']

class ImagesDelete(DeleteView):
    model = Image
    success_url = reverse_lazy('music:images')


def videos(request):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:
        video = Video.objects.all()

        return render(request, 'music/videos.html', {
            'video': video,
            })

class VideosCreate(CreateView):
    model = Video
    fields = ['video_title', 'video_file']

class VideosUpdate(UpdateView):
    model = Video
    fields = ['video_title', 'video_file']

class VideosDelete(DeleteView):
    model = Video
    success_url = reverse_lazy('music:videos')

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}VivaMedia{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Monoton' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class = 'container-fluid'>

        <!--Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">VivaMedia</a>
        </div>

        <!--Items-->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block album_active %}{% endblock %}">
                    <a href="{% url 'music:index' %}">
                    <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;Albums
                    </a>
                </li>
                <li class="{% block video_active %}{% endblock %}">
                    <a href="{% url 'music:videos' %}">
                    <span class="glyphicon glyphicon-facetime-video" aria-hidden="true"></span>&nbsp;Videos
                    </a>
                </li>
                <li class="{% block image_active %}{% endblock %}">
                    <a href="{% url 'music:images' %}">
                    <span class="glyphicon glyphicon-picture" aria-hidden="true"></span>&nbsp;Images
                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type ='text' class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                 <li class="dropdown">
                    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Add Media
                    <span class="cglyphicon glyphicon-plus" aria-hidden="true"></span></button>
                     <ul class="dropdown-menu">
                            <li><a href="{% url 'music:album-add' %}">Add Albums</a></li>
                            <li><a href="{% url 'music:videos-add' %}">Add Video</a></li>
                            <li><a href="{% url 'music:images-add' %}">Add Image</a></li>
                      </ul>
                </li>

                 <li class="">
                    <a href="{% url 'music:logout_user' %}">
                    <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Logout
                    </a>
                </li>
            </ul>

        </div>

    </div>
</nav>
{% block body %}
{% endblock %}

</body>
</html>

music/templates/music/base_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}VivaMedia{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Monoton' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class = 'container-fluid'>

        <!--Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">VivaMedia</a>
        </div>

        <!--Items-->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block album_active %}{% endblock %}">
                    <a href="{% url 'music:index' %}">
                    <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;Albums
                    </a>
                </li>
                <li class="{% block video_active %}{% endblock %}">
                    <a href="{% url 'music:videos' %}">
                    <span class="glyphicon glyphicon-facetime-video" aria-hidden="true"></span>&nbsp;Videos
                    </a>
                </li>
                <li class="{% block image_active %}{% endblock %}">
                    <a href="{% url 'music:images' %}">
                    <span class="glyphicon glyphicon-picture" aria-hidden="true"></span>&nbsp;Images
                    </a>
                </li>
            </ul>



            <ul class="nav navbar-nav navbar-right">
                 <li class="dropdown">
                    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Add Media
                    <span class="cglyphicon glyphicon-plus" aria-hidden="true"></span></button>
                     <ul class="dropdown-menu">
                            <li><a href="{% url 'music:album-add' %}">Add Albums</a></li>
                            <li><a href="{% url 'music:videos-add' %}">Add Video</a></li>
                            <li><a href="{% url 'music:images-add' %}">Add Image</a></li>
                      </ul>
                </li>

                 <li class="">
                    <a href="{% url 'music:logout_user' %}">
                    <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Logout
                    </a>
                </li>
            </ul>

        </div>

    </div>
</nav>
{% block body %}
{% endblock %}

</body>
</html>

music/templates/music/base_others.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}VivaMedia{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Monoton' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class = 'container-fluid'>

        <!--Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">VivaMedia</a>
        </div>

        <!--Items-->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block album_active %}{% endblock %}">
                    <a href="{% url 'music:index' %}">
                    <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;Albums
                    </a>
                </li>
                <li class="{% block video_active %}{% endblock %}">
                    <a href="{% url 'music:videos' %}">
                    <span class="glyphicon glyphicon-facetime-video" aria-hidden="true"></span>&nbsp;Videos
                    </a>
                </li>
                <li class="{% block image_active %}{% endblock %}">
                    <a href="{% url 'music:images' %}">
                    <span class="glyphicon glyphicon-picture" aria-hidden="true"></span>&nbsp;Images
                    </a>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                 <li class="dropdown">
                    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Add Media
                    <span class="cglyphicon glyphicon-plus" aria-hidden="true"></span></button>
                     <ul class="dropdown-menu">
                            <li><a href="{% url 'music:album-add' %}">Add Albums</a></li>
                            <li><a href="{% url 'music:videos-add' %}">Add Video</a></li>
                            <li><a href="{% url 'music:images-add' %}">Add Image</a></li>
                      </ul>
                </li>

                 <li class="">
                    <a href="{% url 'music:logout_user' %}">
                    <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Logout
                    </a>
                </li>
            </ul>

        </div>

    </div>
</nav>
{% block body %}
{% endblock %}

</body>
</html>

music/templates/music/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}VivaMedia{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Monoton' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">VivaMedia</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'music:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'music:login_user' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/detail.html
{% extends 'music/base_detail.html' %}
{% block title %}VivaMedia - Album Details{% endblock %}</title>
{% block album_active %}{% endblock %}

{% block body %}

    <a class = 'btn btn-primary' href="{% url 'music:create_song' album.id %}">Add Music</a><br><br>


    <h1>Album Title: {{ album.album_title }}</h1>
    <h3>Album Artist: {{ album.artist }}</h3><br>

    {% if error_message %}
        <p><strong>{{ error_message}}</strong></p>
    {% endif %}


    <div class="container">
                    <table class="table table-condensed">
                        <thead>
                        <tr>
                            <th>Song Title</th>
                            <th>Play</th>
                            <th>Edit</th>
                            <th>Delete</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for song in album.song_set.all %}
                        <tr>
                            <td>{{ song.song_title }}</td>
                            <td><a href="/media/{{ song.song_file }}">
                    <span class="glyphicon glyphicon-play"></span>
                </a></td>
                            <td><a href="{% url 'music:song-update' song.id %}">
                    <span class="glyphicon glyphicon-edit"></span>
                </a></td>
                            <td><form action="{% url 'music:delete_song' album.id song.id %}" method="post" style="display: inline;">
                {% csrf_token %}
                    <input type="hidden" name="song_id" value="{{ song.id }}" />
                    <button type="submit" class="btn btn-link">
                        <span class="glyphicon glyphicon-trash"></span>
                    </button>
                </form></td>
                        </tr>

                    {% endfor %}

                        </tbody>
  </table>
</div>


{% endblock %}

music/templates/music/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>

    </div>

{% endfor %}

music/templates/music/images.html
{% extends 'music/base_others.html' %}
{% block image_active %}active{% endblock %}

{% block body%}

<style>
  .carousel-inner > .item > img,
  .carousel-inner > .item > a > img {
      width: 70%;
      margin: auto;
  }
</style>
</head>

    {% if image %}



    <div class="container">
      <br>
      <div id="myCarousel" class="carousel slide" data-ride="carousel">


        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
             {% for image in image %}
                {% if forloop.first %}
                  <div class="item active">
                    <img src={{ image.image_file.url }} alt="Chania" width="460" height="345">
                  </div>
                {% endif %}
                    <div class="item ">
                    <img src={{ image.image_file.url }} alt="Chania" width="460" height="345">
                  </div>
             {% endfor %}
        </div>


    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
<br>





        <h3>Here are all your upload images: Click for full size image</h3>

        <ul>
            {% for image in image %}



                <strong>{{ image.image_title }}</strong>
                <li><a href="{{ image.image_file.url }}"><img src="{{ image.image_file.url }}" width="100" height="50"></a></li>

            <!-- Delete Images -->
                <form action="{% url 'music:delete_images' image.id %}" method="post" style="display: inline;">
                {% csrf_token %}
                    <input type="hidden" name="album_id" value="{{ image.id }}" />
                    <button type="submit" class="btn btn-link">
                        <span class="glyphicon glyphicon-trash"></span>
                    </button>
                </form>

        <!-- Edit Images -->
                <a href="{% url 'music:images-update' image.id %}">
                    <span class="glyphicon glyphicon-edit"></span>
                </a>
                <br>
                <br>

            {% endfor %}
        </ul>

    {% else %}
        <h3>You don't have any images</h3>
    {% endif %}
{% endblock%}

music/templates/music/index.html
{% extends 'music/base.html' %}
{% block album_active %}active{% endblock %}

{% block body%}
    {% if albums %}
        <h3>Here are all your uploaded Albums: Click album title for more details</h3><br>

            <div class="container">
                    <table class="table table-condensed">
                        <thead>
                        <tr>
                            <th>Album Title</th>
                            <th>Album Artist</th>
                            <th>Edit</th>
                            <th>Delete</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for album in albums %}
                        <tr>
                            <td><a href="{% url 'music:detail' album.id %}" >{{ album.album_title }}</a></td>
                            <td>{{album.artist}}</td>
                            <td><a href="{% url 'music:album-update' album.id %}">
                    <span class="glyphicon glyphicon-edit"></span>
                </a></td>
                            <td><form action="{% url 'music:album-delete' album.id %}" method="post" style="display: inline;">
                {% csrf_token %}
                    <input type="hidden" name="album_id" value="{{ album.id }}" />
                    <button type="submit" class="btn btn-link">
                        <span class="glyphicon glyphicon-trash"></span>
                    </button>
                </form></td>
                        </tr>

                    {% endfor %}

                        </tbody>
  </table>
</div>


    {% else %}
        <h3>You don't have any albums</h3>
    {% endif %}
{% endblock%}

music/templates/music/login.html
{% extends 'music/base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-4 col-md-4"></div>
        <div class="col-sm-4 col-md-4">
            <div class="span3">
                <div class="well span6" align="center">
                    <h3><center>Log In</center></h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'music:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group" style="">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'music:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

music/templates/music/videos.html
{% extends 'music/base_others.html' %}
{% block video_active %}active{% endblock %}

{% block body%}
    {% if video %}
        <h3>These are all your uploaded videos: Click to play</h3>

        <ul>
            {% for video in video %}
                <strong>{{ video.video_title }}</strong>
                <li><a href="/media/{{ video.video_file }}"><video src="{{ video.video_file.url }}"></video></a></li>

            <!-- Delete Images -->
                <form action="{% url 'music:delete_videos' video.id %}" method="post" style="display: inline;">
                {% csrf_token %}
                    <input type="hidden" name="album_id" value="{{ video.id }}" />
                    <button type="submit" class="btn btn-link">
                        <span class="glyphicon glyphicon-trash"></span>
                    </button>
                </form>

        <!-- Edit Images -->
                <a href="{% url 'music:videos-update' video.id %}">
                    <span class="glyphicon glyphicon-edit"></span>
                </a>
                <br>

            {% endfor %}
        </ul>

    {% else %}
        <h3>You don't have any videos</h3>
    {% endif %}
{% endblock%}